### PR TITLE
S3 service for resume upload / download

### PR DESCRIPTION
**Pull request by aletya**
/s3/upload
- returns url and fields necessary to upload to our S3 bucket (POST)
- can only be called for oneself
- can be called by USER+

/s3/download
- returns url to download user's resume from our S3 bucket (GET)
- can only be called for oneself
- can be called by USER+

/s3/download/:USERID
- returns url to download specific user's resume from our S3 bucket (GET)
- can only be called by ADMIN

### CODE REVIEW

**Review by AydanPirani — APPROVED** [review]
lgtm!

**Review by divyack2 — CHANGES_REQUESTED** [review]
just resolve the merge conflicts and you should be good to go :)

**Comment by aletya** [comment]
> just resolve the merge conflicts and you should be good to go :)

resolved!

**Review by divyack2 — APPROVED** [review]
lgtm!

**Pull request merged**
